### ISSUE TITLE
这是什么情况？

### ISSUE THREAD

**Issue by BoyHarry** [henices/Tcp-DNS-proxy#24]
控制台输出：
H:\GreenSoft\Tools\Tcp-DNS-proxy-master\win>tcpdns.exe -f config.json
[2015-08-16 15:10:04,233][INFO] TCP DNS Proxy, https://github.com/henices/Tcp-DN
S-proxy
[2015-08-16 15:10:04,247][INFO] DNS Servers:
[u'8.8.8.8:53', u'8.8.4.4:53', u'156.154.70.1:53', u'156.154.71.1:53', u'208.67.
222.222:53', u'208.67.220.220:53', u'209.244.0.3:53']
[2015-08-16 15:10:04,247][INFO] Query Timeout: 20.000000
[2015-08-16 15:10:04,247][INFO] Enable Cache: True
[2015-08-16 15:10:04,249][INFO] Enable Switch: True
[2015-08-16 15:10:04,249][INFO] Testing dns server speed ...
[2015-08-16 15:10:47,615][ERROR] 208.67.222.222:53, timed out
[2015-08-16 15:11:21,131][ERROR] 8.8.4.4:53, timed out
[2015-08-16 15:11:59,490][ERROR] 156.154.70.1:53, timed out
[2015-08-16 15:12:19,492][ERROR] 156.154.71.1:53, timed out
[2015-08-16 15:12:39,493][ERROR] 208.67.222.222:53, timed out
[2015-08-16 15:13:42,996][ERROR] 8.8.8.8:53, timed out
[2015-08-16 15:14:15,928][ERROR] 208.67.222.222:53, timed out
[2015-08-16 15:14:16,653][INFO] Now you can set dns server to 0.0.0.0:53
Traceback (most recent call last):
  File "<string>", line 419, in <module>
  File "<string>", line 358, in thread_main
  File "<string>", line 342, in __init__
  File "C:\Users\sunya_000\Documents\Tcp-DNS-proxy-master\GIT\win\build\tcpdns\o
ut00-PYZ.pyz\SocketServer", line 420, in __init__
  File "C:\Users\sunya_000\Documents\Tcp-DNS-proxy-master\GIT\win\build\tcpdns\o
ut00-PYZ.pyz\SocketServer", line 434, in server_bind
  File "C:\Users\sunya_000\Documents\Tcp-DNS-proxy-master\GIT\win\build\tcpdns\o
ut00-PYZ.pyz\socket", line 224, in meth
socket.error: [Errno 10048] 通常每个套接字地址(协议/网络地址/端口)

**Comment by henices** [comment]
这个错误按照提示是端口已经被占用。 使用 netstat -an 查看 UDP 53 端口是否被占用。

可能还涉及权限问题。

**Comment by BoyHarry** [comment]
谢谢！我换了个地址就没报错。
不过test里面全部都是time out真的大丈夫？
而且只能上内网，外网还是连不上，它说什么tried many times

**Comment by henices** [comment]
你的网络到国外的DNS 服务器可能不太稳定，可以尝试修改 tcpdns.json 里的 DNs 服务器地址
