### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'reqdired'

### ISSUE THREAD

**Issue by yuanhuanglin** [henices/Tcp-DNS-proxy#31]
您好！在Ubuntu上运行的时候遇到以下问题。

```
$sudo python tcpdns.py -f tcpdns.json.example
Traceback (most recent call last):
  File "tcpdns.py", line 390, in <module>
    reqdired=False, default=False, help='Stop tcp dns proxy daemon')
  File "/usr/lib/python2.7/argparse.py", line 1294, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'reqdired'

```
请问如何解决？

环境：
- git clone  https://github.com/henices/Tcp-DNS-proxy.git
- git submodule update --init --recursive
- uname -a ： Linux ubuntu-python2-dev 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- python --version ： Python 2.7.12
-  pip list
```
backports-abc (0.4)
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.4.1)
certifi (2016.8.8)
chardet (2.3.0)
configparser (3.5.0)
decorator (4.0.10)
dnspython (1.12.0)
docutils (0.12)
entrypoints (0.2.2)
functools32 (3.2.3.post2)
gevent (1.1.2)
greenlet (0.4.10)
html5lib (0.999)
ipykernel (4.4.1)
ipython (5.0.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.3.0)
jupyter-console (5.0.0)
jupyter-core (4.1.0)
lockfile (0.12.2)
lxml (3.5.0)
MarkupSafe (0.23)
mistune (0.7.3)
nbconvert (4.2.0)
nbformat (4.1.0)
notebook (4.2.2)
numpy (1.11.1)
pandas (0.18.1)
pathlib2 (2.1.0)
pexpect (4.2.0)
pickleshare (0.7.3)
Pillow (3.1.2)
pip (8.1.2)
prompt-toolkit (1.0.3)
ptyprocess (0.5.1)
pycrypto (2.6.1)
Pygments (2.1.3)
PyMySQL (0.7.2)
python-dateutil (2.5.3)
pytz (2016.6.1)
pyzmq (15.4.0)
qtconsole (4.2.1)
roman (2.0.0)
scipy (0.18.0)
setuptools (25.1.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
SQLAlchemy (1.0.11)
terminado (0.6)
tornado (4.4.1)
traitlets (4.2.2)
tushare (0.5.0)
wcwidth (0.1.7)
wheel (0.29.0)
widgetsnbextension (1.2.6)

```

**Comment by yuanhuanglin** [comment]
找到原因了， 是拼写错误。
TypeError: __init__() got an unexpected keyword argument 'reqdired'
修改前：
```
    parser.add_argument('-s', dest="stop_daemon", action='store_true',
            reqdired=False, default=False, help='Stop tcp dns proxy daemon')
    args = parser.parse_args()

```
修改后
```    parser.add_argument('-s', dest="stop_daemon", action='store_true',
            required=False, default=False, help='Stop tcp dns proxy daemon')
    args = parser.parse_args()
```

**Comment by henices** [comment]
没有在代码中发现 reqdired
